### PR TITLE
Resolve interpreter correctly for non-PyCharm IDEs

### LINKED ISSUE #41: Project interpreter is not resolved correctly on CLion
On CLion, [`ProjectRootManager.getInstance(project).projectSdk`](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/blob/e8bf705276e9fbade952073e09e0b62d1391b26a/src/main/kotlin/com/insyncwithfoo/pyrightls/Project.kt#L14-L15) returns `null`.

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
Presumably fixes #41. Not tested.

### CODE REVIEW

**Comment by bzoracler** [comment]
I've tested the following IDEs on Windows (latest stable versions unless otherwise indicated):
* CLion - works
* IntelliJ Ultimate - works
* RustRover 2024.1 EAP - works
* Rider - works

The results all look like this:

```pycon
>>> from collections.abc import Callable
>>>
>>> v: Callable[[int], bool] = 1
                               ^
Pyright: Expression of type "Literal[1]" is incompatible with declared type "(int) -> bool"
   Type "Literal[1]" is incompatible with type "(int) -> bool" (reportAssignmentType)
```

**Comment by InSyncWithFoo** [comment]
@bzoracler Thanks a lot! That saved me an unimaginably vast amount of work.

Could you show me the corresponding log entries? If that's something you don't want to show publicly, you could redact private parts and/or send me an email at <i>&lt;this account's name&gt;@gmail.com</i>.

**Comment by InSyncWithFoo** [comment]
After hours of debugging I conclude that a `null` interpreter is not the cause of what I saw in #41.

Painfully, that means I have two problems, one here and one has yet to be discovered.

**Comment by bzoracler** [comment]
I've sent over a log file from a CLion session - hopefully that helps.

**Comment by InSyncWithFoo** [comment]
@bzoracler Thanks, but the file doesn't contain any LSP log entries, which would look something like this:

```text
#c.i.p.l.i.c.Lsp4jServerConnector - --> PyrightLSDescriptor@project: {"jsonrpc":"2.0", ...}
#c.i.p.l.i.c.Lsp4jServerConnector - <-- PyrightLSDescriptor@project: {"jsonrpc":"2.0", ...}
```

Perhaps you forgot to [enable logging](https://insyncwithfoo.github.io/pyright-for-pycharm/how-to/#how-to-enable-language-server-logging)?

Specifically, what I want to look at the most is the `didChangeConfiguration` request as [sent by `Listener`](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/blob/a95bea0f9b5247ab01b4025aa907c3ad1e1a27aa/src/main/kotlin/com/insyncwithfoo/pyrightls/server/Listener.kt#L38-L42) on server initialization. If the interpreter is not passed correctly, the JSON data will have no `params.settings.python.pythonPath` property, as shown [here](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/issues/41#issuecomment-2106011601).

**Comment by InSyncWithFoo** [comment]
The logic was copied from [`PyInterpreterInspection`](https://github.com/JetBrains/intellij-community/blob/d0b2eeb2e6ecd0873f1a32e8c03a7c292a9e9990/python/src/com/jetbrains/python/inspections/PyInterpreterInspection.java#L106). It sure feels good randomly stumping into something that would help solve a 2-month-old issue.

**Pull request merged**
